import { Inject, Injectable } from '@nestjs/common';
import {
  AppError,
  ErrorFactory,
  INTEGRATION_EVENT_PUBLISHER,
  IntegrationEventPublisher,
  OPERATIONAL_EVENTS,
  Result,
  UseCase,
} from '../../../../shared-kernel';
import { DrawShift } from '../../domain/entities';
import { DRAWS_REPOSITORY, DrawsRepository } from '../../domain/ports';
import { publishDrawShiftEvent } from '../events';

export type AutoGenerateDrawShiftsCommand = {
  date?: string;
};

export type AutoGenerateDrawShiftsResult = {
  date: string;
  createdOrExistingCount: number;
  shifts: DrawShift[];
};

@Injectable()
export class AutoGenerateDrawShiftsUseCase extends UseCase<
  AutoGenerateDrawShiftsCommand,
  AutoGenerateDrawShiftsResult,
  AppError
> {
  constructor(
    @Inject(DRAWS_REPOSITORY)
    private readonly drawsRepository: DrawsRepository,
    @Inject(INTEGRATION_EVENT_PUBLISHER)
    private readonly eventPublisher?: IntegrationEventPublisher,
  ) {
    super();
  }

  async execute(
    input: AutoGenerateDrawShiftsCommand,
  ): Promise<Result<AutoGenerateDrawShiftsResult, AppError>> {
    try {
      const date = input.date ?? this.today();
      const shifts = await this.drawsRepository.autoGenerateShifts({ date });

      for (const shift of shifts) {
        publishDrawShiftEvent(
          this.eventPublisher,
          OPERATIONAL_EVENTS.drawShiftOpened,
          shift,
        );
      }

      return Result.success({
        date,
        createdOrExistingCount: shifts.length,
        shifts,
      });
    } catch (error) {
      return ErrorFactory.useCase(
        error instanceof Error
          ? error.message
          : 'Could not auto-generate draw shifts',
        error,
      );
    }
  }

  private today(): string {
    return new Date().toISOString().slice(0, 10);
  }
}
