import {
  IntegrationEventInput,
  IntegrationEventPublisher,
  OPERATIONAL_EVENTS,
} from '../../../../shared-kernel';
import { DrawsRepository } from '../../domain';
import { AutoGenerateDrawShiftsUseCase } from './auto-generate-draw-shifts.use-case';

describe('AutoGenerateDrawShiftsUseCase', () => {
  const repository: jest.Mocked<DrawsRepository> = {
    createConfiguration: jest.fn(),
    findConfigurationById: jest.fn(),
    updateConfiguration: jest.fn(),
    getConfigurationDeleteImpact: jest.fn(),
    softDeleteConfiguration: jest.fn(),
    hardDeleteConfiguration: jest.fn(),
    listConfigurations: jest.fn(),
    autoGenerateShifts: jest.fn(),
    openShift: jest.fn(),
    blockShift: jest.fn(),
    reopenShift: jest.fn(),
    closeShift: jest.fn(),
    listShifts: jest.fn(),
    listActiveShifts: jest.fn(),
  };

  const events: IntegrationEventInput[] = [];
  const publisher: IntegrationEventPublisher = {
    publish: (event) => events.push(event),
  };

  let useCase: AutoGenerateDrawShiftsUseCase;

  beforeEach(() => {
    jest.clearAllMocks();
    events.length = 0;
    repository.autoGenerateShifts.mockResolvedValue([
      {
        id: 'shift-id',
        date: '2026-07-07',
        status: 'ABIERTO',
        createdAt: new Date('2026-07-07T08:00:00.000Z'),
        updatedAt: new Date('2026-07-07T08:00:00.000Z'),
        configuration: {
          id: 'configuration-id',
          code: 'nacional-11am',
          time: '11:00:00',
          tuesdayOnly: false,
          autoGenerateShifts: true,
          singleDate: null,
          lockSecondsBefore: 60,
          reopenSecondsAfter: 600,
          active: true,
          deletedAt: null,
          deletionReason: null,
          createdAt: new Date('2026-07-07T08:00:00.000Z'),
          updatedAt: new Date('2026-07-07T08:00:00.000Z'),
        },
      },
    ]);
    useCase = new AutoGenerateDrawShiftsUseCase(repository, publisher);
  });

  it('auto-generates shifts for the requested date and publishes realtime events', async () => {
    const result = await useCase.execute({ date: '2026-07-07' });

    expect(result.isSuccess).toBe(true);
    if (result.isFailure) throw result.error;
    expect(repository.autoGenerateShifts.mock.calls[0][0]).toEqual({
      date: '2026-07-07',
    });
    expect(result.value).toMatchObject({
      date: '2026-07-07',
      createdOrExistingCount: 1,
    });
    expect(events[0]).toMatchObject({
      name: OPERATIONAL_EVENTS.drawShiftOpened,
      aggregateId: 'shift-id',
      payload: {
        shiftId: 'shift-id',
        drawCode: 'nacional-11am',
        status: 'ABIERTO',
      },
    });
  });
});
