import { Injectable } from '@nestjs/common';
import { Prisma, turno_estado } from '@prisma/client';
import { buildOffsetPagination, getOffsetSkip } from '../../../../../common';
import { PrismaService } from '../../../../../infrastructure/database/prisma';
import { PaginatedResult } from '../../../../../shared-kernel';
import {
  DeleteDrawConfigurationResult,
  DrawConfiguration,
  DrawConfigurationDeleteImpact,
  DrawShift,
} from '../../../domain/entities';
import {
  AutoGenerateDrawShiftsInput,
  CreateDrawConfigurationInput,
  DrawsRepository,
  HardDeleteDrawConfigurationInput,
  ListActiveDrawShiftsQuery,
  ListDrawConfigurationsQuery,
  ListDrawShiftsQuery,
  OpenDrawShiftInput,
  SoftDeleteDrawConfigurationInput,
  UpdateDrawConfigurationInput,
} from '../../../domain/ports';

const shiftInclude = {
  sorteos_config: true,
} satisfies Prisma.turnosInclude;

type DrawShiftRecord = Prisma.turnosGetPayload<{
  include: typeof shiftInclude;
}>;

@Injectable()
export class PrismaDrawsRepository implements DrawsRepository {
  constructor(private readonly prisma: PrismaService) {}

  async createConfiguration(
    input: CreateDrawConfigurationInput,
  ): Promise<DrawConfiguration> {
    try {
      const configuration = await this.prisma.sorteos_config.create({
        data: {
          codigo: input.code,
          hora: this.toTimeDate(input.time),
          solo_martes: input.tuesdayOnly ?? false,
          auto_generar_turnos: input.autoGenerateShifts ?? true,
          fecha_unica: input.singleDate
            ? this.toDateOnly(input.singleDate)
            : null,
          lock_segundos_antes: input.lockSecondsBefore ?? 60,
          reopen_segundos_despues: input.reopenSecondsAfter ?? 600,
          activo: input.active ?? true,
        },
      });

      return this.mapConfiguration(configuration);
    } catch (error) {
      throw this.toDrawsError(error);
    }
  }

  async listConfigurations(
    query: ListDrawConfigurationsQuery,
  ): Promise<PaginatedResult<DrawConfiguration>> {
    const where: Prisma.sorteos_configWhereInput = {
      eliminado_en: null,
      ...(query.active !== undefined && { activo: query.active }),
    };

    const [configurations, total] = await this.prisma.$transaction([
      this.prisma.sorteos_config.findMany({
        where,
        orderBy: this.toConfigurationOrderBy(query),
        skip: getOffsetSkip(query),
        take: query.limit,
      }),
      this.prisma.sorteos_config.count({ where }),
    ]);

    return buildOffsetPagination(
      configurations.map((configuration) =>
        this.mapConfiguration(configuration),
      ),
      total,
      query,
    );
  }

  async findConfigurationById(
    configurationId: string,
  ): Promise<DrawConfiguration | null> {
    const configuration = await this.prisma.sorteos_config.findUnique({
      where: {
        id: configurationId,
      },
    });

    return configuration ? this.mapConfiguration(configuration) : null;
  }

  async updateConfiguration(
    input: UpdateDrawConfigurationInput,
  ): Promise<DrawConfiguration | null> {
    const configuration = await this.prisma.sorteos_config.findUnique({
      where: {
        id: input.configurationId,
      },
    });

    if (!configuration) {
      return null;
    }

    try {
      const updatedConfiguration = await this.prisma.sorteos_config.update({
        where: {
          id: input.configurationId,
        },
        data: {
          ...(input.code !== undefined && { codigo: input.code }),
          ...(input.time !== undefined && {
            hora: this.toTimeDate(input.time),
          }),
          ...(input.tuesdayOnly !== undefined && {
            solo_martes: input.tuesdayOnly,
          }),
          ...(input.autoGenerateShifts !== undefined && {
            auto_generar_turnos: input.autoGenerateShifts,
            fecha_unica:
              input.autoGenerateShifts === true
                ? null
                : input.singleDate
                  ? this.toDateOnly(input.singleDate)
                  : undefined,
          }),
          ...(input.singleDate !== undefined &&
            input.autoGenerateShifts !== true && {
              fecha_unica: input.singleDate
                ? this.toDateOnly(input.singleDate)
                : null,
            }),
          ...(input.lockSecondsBefore !== undefined && {
            lock_segundos_antes: input.lockSecondsBefore,
          }),
          ...(input.reopenSecondsAfter !== undefined && {
            reopen_segundos_despues: input.reopenSecondsAfter,
          }),
          ...(input.active !== undefined && { activo: input.active }),
          actualizado_en: new Date(),
        },
      });

      return this.mapConfiguration(updatedConfiguration);
    } catch (error) {
      throw this.toDrawsError(error);
    }
  }

  async getConfigurationDeleteImpact(
    configurationId: string,
  ): Promise<DrawConfigurationDeleteImpact | null> {
    return this.buildDeleteImpact(configurationId);
  }

  async softDeleteConfiguration(
    input: SoftDeleteDrawConfigurationInput,
  ): Promise<DeleteDrawConfigurationResult | null> {
    const impact = await this.buildDeleteImpact(input.configurationId);

    if (!impact) return null;

    await this.prisma.sorteos_config.update({
      where: { id: input.configurationId },
      data: {
        activo: false,
        eliminado_en: new Date(),
        motivo_eliminacion: input.reason,
        actualizado_en: new Date(),
      },
    });

    return {
      configurationId: input.configurationId,
      mode: 'SOFT',
      deleted: true,
      impact,
    };
  }

  async hardDeleteConfiguration(
    input: HardDeleteDrawConfigurationInput,
  ): Promise<DeleteDrawConfigurationResult | null> {
    const impact = await this.buildDeleteImpact(input.configurationId);

    if (!impact) return null;

    await this.prisma.$transaction(async (tx) => {
      await tx.pagos_premios.deleteMany({
        where: {
          ventas: {
            turnos: { is: { config_id: input.configurationId } },
          },
        },
      });
      await tx.venta_detalle.deleteMany({
        where: {
          ventas: {
            turnos: { is: { config_id: input.configurationId } },
          },
        },
      });
      await tx.ventas.deleteMany({
        where: {
          turnos: { is: { config_id: input.configurationId } },
        },
      });
      await tx.resultados.deleteMany({
        where: {
          turnos: {
            config_id: input.configurationId,
          },
        },
      });
      await tx.numeros_bloqueados.deleteMany({
        where: {
          turnos: { is: { config_id: input.configurationId } },
        },
      });
      await tx.turnos.deleteMany({
        where: {
          config_id: input.configurationId,
        },
      });
      await tx.limites_numero.deleteMany({
        where: {
          config_id: input.configurationId,
        },
      });
      await tx.sorteos_config.delete({
        where: {
          id: input.configurationId,
        },
      });
    });

    return {
      configurationId: input.configurationId,
      mode: 'HARD',
      deleted: true,
      impact,
    };
  }

  async autoGenerateShifts(
    input: AutoGenerateDrawShiftsInput,
  ): Promise<DrawShift[]> {
    const date = this.toDateOnly(input.date);
    const configurations = await this.prisma.sorteos_config.findMany({
      where: {
        activo: true,
        eliminado_en: null,
        OR: [
          { auto_generar_turnos: true, fecha_unica: null },
          { auto_generar_turnos: false, fecha_unica: date },
        ],
      },
      orderBy: [{ hora: 'asc' }, { codigo: 'asc' }],
    });

    const created: DrawShiftRecord[] = [];

    for (const configuration of configurations) {
      if (!this.isConfigurationOperableOnDate(configuration, date)) {
        continue;
      }

      const existing = await this.prisma.turnos.findUnique({
        where: {
          fecha_config_id: {
            fecha: date,
            config_id: configuration.id,
          },
        },
      });

      if (existing) continue;

      const shift = await this.prisma.turnos.create({
        data: {
          fecha: date,
          config_id: configuration.id,
          estado: turno_estado.ABIERTO,
        },
        include: shiftInclude,
      });
      created.push(shift);
    }

    return created.map((shift) => this.mapShift(shift));
  }

  async openShift(input: OpenDrawShiftInput): Promise<DrawShift> {
    try {
      const date = this.toDateOnly(input.date);
      const configuration = await this.prisma.sorteos_config.findUnique({
        where: {
          id: input.configurationId,
        },
      });

      if (!configuration) {
        throw new Error('Draw configuration does not exist');
      }

      if (!this.isConfigurationOperableOnDate(configuration, date)) {
        throw new Error('Draw configuration is not operable on this date');
      }

      const existingShift = await this.prisma.turnos.findUnique({
        where: {
          fecha_config_id: {
            fecha: date,
            config_id: input.configurationId,
          },
        },
        include: shiftInclude,
      });

      if (existingShift) {
        return this.mapShift(existingShift);
      }

      const shift = await this.prisma.turnos.create({
        data: {
          fecha: date,
          config_id: input.configurationId,
          estado: turno_estado.ABIERTO,
        },
        include: shiftInclude,
      });

      return this.mapShift(shift);
    } catch (error) {
      throw this.toDrawsError(error);
    }
  }

  async closeShift(shiftId: string): Promise<DrawShift | null> {
    try {
      const existingShift = await this.prisma.turnos.findUnique({
        where: {
          id: shiftId,
        },
        include: shiftInclude,
      });

      if (!existingShift) {
        return null;
      }

      if (existingShift.estado === turno_estado.CERRADO) {
        return this.mapShift(existingShift);
      }

      const shift = await this.prisma.turnos.update({
        where: {
          id: shiftId,
        },
        data: {
          estado: turno_estado.CERRADO,
        },
        include: shiftInclude,
      });

      return this.mapShift(shift);
    } catch (error) {
      throw this.toDrawsError(error);
    }
  }

  async blockShift(shiftId: string): Promise<DrawShift | null> {
    try {
      return this.transitionShift(shiftId, turno_estado.BLOQUEO, [
        turno_estado.ABIERTO,
        turno_estado.BLOQUEO,
      ]);
    } catch (error) {
      throw this.toDrawsError(error);
    }
  }

  async reopenShift(shiftId: string): Promise<DrawShift | null> {
    try {
      return this.transitionShift(shiftId, turno_estado.ABIERTO, [
        turno_estado.ABIERTO,
        turno_estado.BLOQUEO,
      ]);
    } catch (error) {
      throw this.toDrawsError(error);
    }
  }

  async listShifts(
    query: ListDrawShiftsQuery,
  ): Promise<PaginatedResult<DrawShift>> {
    if (query.date) {
      await this.autoGenerateShifts({ date: query.date });
    }

    const where: Prisma.turnosWhereInput = {
      ...(query.date && { fecha: this.toDateOnly(query.date) }),
      ...(query.status && { estado: query.status }),
    };

    const [shifts, total] = await this.prisma.$transaction([
      this.prisma.turnos.findMany({
        where,
        include: shiftInclude,
        orderBy: this.toShiftOrderBy(query),
        skip: getOffsetSkip(query),
        take: query.limit,
      }),
      this.prisma.turnos.count({ where }),
    ]);

    return buildOffsetPagination(
      shifts.map((shift) => this.mapShift(shift)),
      total,
      query,
    );
  }

  async listActiveShifts(
    query: ListActiveDrawShiftsQuery,
  ): Promise<PaginatedResult<DrawShift>> {
    if (query.date) {
      await this.autoGenerateShifts({ date: query.date });
    }

    const where: Prisma.turnosWhereInput = {
      ...(query.date && { fecha: this.toDateOnly(query.date) }),
      estado: {
        in: [turno_estado.ABIERTO, turno_estado.BLOQUEO],
      },
    };

    const [shifts, total] = await this.prisma.$transaction([
      this.prisma.turnos.findMany({
        where,
        include: shiftInclude,
        orderBy: this.toShiftOrderBy(query),
        skip: getOffsetSkip(query),
        take: query.limit,
      }),
      this.prisma.turnos.count({ where }),
    ]);

    return buildOffsetPagination(
      shifts.map((shift) => this.mapShift(shift)),
      total,
      query,
    );
  }

  private async transitionShift(
    shiftId: string,
    nextStatus: turno_estado,
    allowedStatuses: turno_estado[],
  ): Promise<DrawShift | null> {
    const existingShift = await this.prisma.turnos.findUnique({
      where: {
        id: shiftId,
      },
      include: shiftInclude,
    });

    if (!existingShift) {
      return null;
    }

    if (!allowedStatuses.includes(existingShift.estado)) {
      throw new Error(
        `Cannot transition draw shift from ${existingShift.estado} to ${nextStatus}`,
      );
    }

    if (existingShift.estado === nextStatus) {
      return this.mapShift(existingShift);
    }

    const shift = await this.prisma.turnos.update({
      where: {
        id: shiftId,
      },
      data: {
        estado: nextStatus,
      },
      include: shiftInclude,
    });

    return this.mapShift(shift);
  }

  private mapShift(shift: DrawShiftRecord): DrawShift {
    return {
      id: shift.id,
      date: this.formatDateOnly(shift.fecha),
      status: shift.estado,
      createdAt: shift.creado_en,
      updatedAt: shift.actualizado_en,
      configuration: this.mapConfiguration(shift.sorteos_config),
    };
  }

  private toConfigurationOrderBy(
    query: ListDrawConfigurationsQuery,
  ): Prisma.sorteos_configOrderByWithRelationInput[] {
    const direction = query.sortDirection;

    switch (query.sortBy) {
      case 'code':
        return [{ codigo: direction }, { hora: 'asc' }, { id: 'asc' }];
      case 'active':
        return [{ activo: direction }, { hora: 'asc' }, { id: 'asc' }];
      case 'createdAt':
        return [{ creado_en: direction }, { id: 'asc' }];
      case 'updatedAt':
        return [{ actualizado_en: direction }, { id: 'asc' }];
      case 'time':
      default:
        return [{ hora: direction }, { codigo: 'asc' }, { id: 'asc' }];
    }
  }

  private toShiftOrderBy(
    query: ListDrawShiftsQuery | ListActiveDrawShiftsQuery,
  ): Prisma.turnosOrderByWithRelationInput[] {
    const direction = query.sortDirection;

    switch (query.sortBy) {
      case 'status':
        return [{ estado: direction }, { fecha: 'desc' }, { id: 'asc' }];
      case 'createdAt':
        return [{ creado_en: direction }, { id: 'asc' }];
      case 'updatedAt':
        return [{ actualizado_en: direction }, { id: 'asc' }];
      case 'configurationTime':
        return [{ sorteos_config: { hora: direction } }, { fecha: 'desc' }];
      case 'configurationCode':
        return [{ sorteos_config: { codigo: direction } }, { fecha: 'desc' }];
      case 'date':
      default:
        return [
          { fecha: direction },
          { sorteos_config: { hora: 'asc' } },
          { id: 'asc' },
        ];
    }
  }

  private mapConfiguration(
    configuration: Prisma.sorteos_configGetPayload<Record<string, never>>,
  ): DrawConfiguration {
    return {
      id: configuration.id,
      code: configuration.codigo,
      time: this.formatTime(configuration.hora),
      tuesdayOnly: configuration.solo_martes,
      autoGenerateShifts: configuration.auto_generar_turnos,
      singleDate: configuration.fecha_unica
        ? this.formatDateOnly(configuration.fecha_unica)
        : null,
      lockSecondsBefore: configuration.lock_segundos_antes,
      reopenSecondsAfter: configuration.reopen_segundos_despues,
      active: configuration.activo,
      deletedAt: configuration.eliminado_en,
      deletionReason: configuration.motivo_eliminacion,
      createdAt: configuration.creado_en,
      updatedAt: configuration.actualizado_en,
    };
  }

  private async buildDeleteImpact(
    configurationId: string,
  ): Promise<DrawConfigurationDeleteImpact | null> {
    const configuration = await this.prisma.sorteos_config.findUnique({
      where: { id: configurationId },
    });

    if (!configuration) return null;

    const [
      shifts,
      sales,
      saleDetails,
      results,
      prizePayments,
      blockedNumbers,
      numberLimits,
    ] = await this.prisma.$transaction([
      this.prisma.turnos.count({ where: { config_id: configurationId } }),
      this.prisma.ventas.count({
        where: { turnos: { is: { config_id: configurationId } } },
      }),
      this.prisma.venta_detalle.count({
        where: {
          ventas: { turnos: { is: { config_id: configurationId } } },
        },
      }),
      this.prisma.resultados.count({
        where: { turnos: { config_id: configurationId } },
      }),
      this.prisma.pagos_premios.count({
        where: {
          ventas: { turnos: { is: { config_id: configurationId } } },
        },
      }),
      this.prisma.numeros_bloqueados.count({
        where: { turnos: { is: { config_id: configurationId } } },
      }),
      this.prisma.limites_numero.count({
        where: { config_id: configurationId },
      }),
    ]);

    return {
      configurationId,
      code: configuration.codigo,
      active: configuration.activo,
      deletedAt: configuration.eliminado_en,
      counts: {
        shifts,
        sales,
        saleDetails,
        results,
        prizePayments,
        blockedNumbers,
        numberLimits,
      },
      requiresConfirmation:
        shifts +
          sales +
          saleDetails +
          results +
          prizePayments +
          blockedNumbers +
          numberLimits >
        0,
    };
  }

  private isConfigurationOperableOnDate(
    configuration: Prisma.sorteos_configGetPayload<Record<string, never>>,
    date: Date,
  ): boolean {
    if (!configuration.activo || configuration.eliminado_en) return false;

    if (!configuration.auto_generar_turnos && !configuration.fecha_unica) {
      return false;
    }

    const singleDate = configuration.fecha_unica;
    if (
      !configuration.auto_generar_turnos &&
      singleDate &&
      this.formatDateOnly(singleDate) !== this.formatDateOnly(date)
    ) {
      return false;
    }

    if (configuration.solo_martes && date.getUTCDay() !== 2) {
      return false;
    }

    return true;
  }

  private toTimeDate(time: string): Date {
    const [hours = 0, minutes = 0, seconds = 0] = time
      .split(':')
      .map((part) => Number(part));

    return new Date(Date.UTC(1970, 0, 1, hours, minutes, seconds));
  }

  private formatTime(time: Date): string {
    return time.toISOString().slice(11, 19);
  }

  private toDateOnly(date: string): Date {
    return new Date(`${date}T00:00:00.000Z`);
  }

  private formatDateOnly(date: Date): string {
    return date.toISOString().slice(0, 10);
  }

  private toDrawsError(error: unknown): Error {
    if (error instanceof Prisma.PrismaClientKnownRequestError) {
      if (error.code === 'P2002') {
        return new Error('Draw resource already exists');
      }

      if (error.code === 'P2003') {
        return new Error('Draw resource references an invalid record');
      }
    }

    return error instanceof Error ? error : new Error('Could not persist draw');
  }
}
