import {
  OffsetPaginationQuery,
  PaginatedResult,
} from '../../../../shared-kernel';
import {
  DeleteDrawConfigurationResult,
  DrawConfiguration,
  DrawConfigurationDeleteImpact,
  DrawShift,
} from '../entities';

export const DRAWS_REPOSITORY = Symbol('DRAWS_REPOSITORY');

export type CreateDrawConfigurationInput = {
  code: string;
  time: string;
  tuesdayOnly?: boolean;
  autoGenerateShifts?: boolean;
  singleDate?: string | null;
  lockSecondsBefore?: number;
  reopenSecondsAfter?: number;
  active?: boolean;
};

export type UpdateDrawConfigurationInput = {
  configurationId: string;
  code?: string;
  time?: string;
  tuesdayOnly?: boolean;
  autoGenerateShifts?: boolean;
  singleDate?: string | null;
  lockSecondsBefore?: number;
  reopenSecondsAfter?: number;
  active?: boolean;
};

export type SoftDeleteDrawConfigurationInput = {
  configurationId: string;
  reason?: string;
};

export type HardDeleteDrawConfigurationInput = {
  configurationId: string;
  reason?: string;
};

export type ListDrawConfigurationsQuery = OffsetPaginationQuery & {
  active?: boolean;
};

export type OpenDrawShiftInput = {
  configurationId: string;
  date: string;
};

export type ListDrawShiftsQuery = OffsetPaginationQuery & {
  date?: string;
  status?: DrawShift['status'];
};

export type ListActiveDrawShiftsQuery = OffsetPaginationQuery & {
  date?: string;
};

export type AutoGenerateDrawShiftsInput = {
  date: string;
};

export interface DrawsRepository {
  createConfiguration(
    input: CreateDrawConfigurationInput,
  ): Promise<DrawConfiguration>;
  findConfigurationById(
    configurationId: string,
  ): Promise<DrawConfiguration | null>;
  updateConfiguration(
    input: UpdateDrawConfigurationInput,
  ): Promise<DrawConfiguration | null>;
  getConfigurationDeleteImpact(
    configurationId: string,
  ): Promise<DrawConfigurationDeleteImpact | null>;
  softDeleteConfiguration(
    input: SoftDeleteDrawConfigurationInput,
  ): Promise<DeleteDrawConfigurationResult | null>;
  hardDeleteConfiguration(
    input: HardDeleteDrawConfigurationInput,
  ): Promise<DeleteDrawConfigurationResult | null>;
  listConfigurations(
    query: ListDrawConfigurationsQuery,
  ): Promise<PaginatedResult<DrawConfiguration>>;
  autoGenerateShifts(input: AutoGenerateDrawShiftsInput): Promise<DrawShift[]>;
  openShift(input: OpenDrawShiftInput): Promise<DrawShift>;
  blockShift(shiftId: string): Promise<DrawShift | null>;
  reopenShift(shiftId: string): Promise<DrawShift | null>;
  closeShift(shiftId: string): Promise<DrawShift | null>;
  listShifts(query: ListDrawShiftsQuery): Promise<PaginatedResult<DrawShift>>;
  listActiveShifts(
    query: ListActiveDrawShiftsQuery,
  ): Promise<PaginatedResult<DrawShift>>;
}
