import { Module } from '@nestjs/common';
import { DatabaseModule } from '../../infrastructure/database/database.module';
import { IdentityAccessModule } from '../identity-access';
import {
  AutoGenerateDrawShiftsUseCase,
  BlockDrawShiftUseCase,
  CloseDrawShiftUseCase,
  CreateDrawConfigurationUseCase,
  GetDrawConfigurationDeleteImpactUseCase,
  GetDrawConfigurationUseCase,
  HardDeleteDrawConfigurationUseCase,
  ListActiveDrawShiftsUseCase,
  ListDrawConfigurationsUseCase,
  ListDrawShiftsUseCase,
  OpenDrawShiftUseCase,
  ReopenDrawShiftUseCase,
  SoftDeleteDrawConfigurationUseCase,
  UpdateDrawConfigurationUseCase,
} from './application';
import { DRAWS_REPOSITORY } from './domain';
import { PrismaDrawsRepository } from './infrastructure';
import { DrawsController } from './presentation';

@Module({
  imports: [DatabaseModule, IdentityAccessModule],
  controllers: [DrawsController],
  providers: [
    PrismaDrawsRepository,
    AutoGenerateDrawShiftsUseCase,
    BlockDrawShiftUseCase,
    CloseDrawShiftUseCase,
    CreateDrawConfigurationUseCase,
    GetDrawConfigurationDeleteImpactUseCase,
    GetDrawConfigurationUseCase,
    HardDeleteDrawConfigurationUseCase,
    ListActiveDrawShiftsUseCase,
    ListDrawConfigurationsUseCase,
    ListDrawShiftsUseCase,
    OpenDrawShiftUseCase,
    ReopenDrawShiftUseCase,
    SoftDeleteDrawConfigurationUseCase,
    UpdateDrawConfigurationUseCase,
    {
      provide: DRAWS_REPOSITORY,
      useExisting: PrismaDrawsRepository,
    },
  ],
  exports: [
    BlockDrawShiftUseCase,
    CloseDrawShiftUseCase,
    CreateDrawConfigurationUseCase,
    GetDrawConfigurationDeleteImpactUseCase,
    GetDrawConfigurationUseCase,
    AutoGenerateDrawShiftsUseCase,
    HardDeleteDrawConfigurationUseCase,
    ListActiveDrawShiftsUseCase,
    ListDrawConfigurationsUseCase,
    ListDrawShiftsUseCase,
    OpenDrawShiftUseCase,
    ReopenDrawShiftUseCase,
    SoftDeleteDrawConfigurationUseCase,
    UpdateDrawConfigurationUseCase,
  ],
})
export class DrawsModule {}
